import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./style.css";
import Title from "./components/title/title";
import Sidebar from "./components/sidebar/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Title />

        <div className="grid grid-cols-12 h-lvh ">
          <div className="col-span-2 border-r-2 static h-auto ">
            <Sidebar />
          </div>
          <div className="col-span-10 bg-[#faf9f8] ">{children}</div>
        </div>
      </body>
    </html>
  );
}
